#!/bin/bash

# Add 3 months (90 days) to all commit dates
git filter-repo --commit-callback '
    import time
    from datetime import datetime, timedelta

    # Define the offset (90 days)
    offset = timedelta(days=90)

    # Convert author date and committer date to datetime, add the offset, and convert back to timestamp
    commit.author_date = str(int(time.mktime((datetime.fromtimestamp(int(commit.author_date)) + offset).timetuple())))
    commit.committer_date = str(int(time.mktime((datetime.fromtimestamp(int(commit.committer_date)) + offset).timetuple())))
'

# Force push the changes
git push --force --tags origin refs/heads/MennaEdit
